#!/usr/bin/env sh

spacebar -m config position             bottom
spacebar -m config height               37
spacebar -m config title                off
spacebar -m config spaces               on
spacebar -m config clock                off
spacebar -m config power                on
spacebar -m config padding_left         50
# spacebar -m config padding_right        20
# spacebar -m config spacing_left         25
# spacebar -m config spacing_right        15
spacebar -m config text_font            "Fira Sans Condensed:Light:16.0"

# spacebar -m config icon_font            "Font Awesome 5 Free:Solid:15.0"

spacebar -m config background_color     0xff00ffffff
# spacebar -m config background_color     'rgba(37, 46, 50, 0.5)'
# spacebar -m config foreground_color     0xff000000
spacebar -m config foreground_color     0xFFFFFFFFFF
# spacebar -m config space_icon_color     0xff458588
spacebar -m config space_icon_color     0xFFC51162 
spacebar -m config power_icon_color     0xffcd950c
# spacebar -m config battery_icon_color   0xffd75f5f
# spacebar -m config dnd_icon_color       0xffa8a8a8
# spacebar -m config clock_icon_color     0xffa8a8a8
spacebar -m config power_icon_strip      
# spacebar -m config space_icon_strip     I II III IV V VI VII VIII IX X
# spacebar -m config space_icon_strip     1 2 3 4 5 6 7 8 9 
# spacebar -m config space_icon_strip     one two three four five six seven eight nine ten
spacebar -m config space_icon_strip      un deux trois quatre cinq six sept huit neuf dix
# spacebar -m config space_icon           
# spacebar -m config clock_icon           
# spacebar -m config dnd_icon             
# spacebar -m config clock_format         "%d/%m/%y %R"
spacebar -m config right_shell          off
spacebar -m config right_shell_icon     ︁ 
# spacebar -m config right_shell_command  "whoami"
 
# spacebar -m config center_shell          on
# spacebar -m config center_shell_icon 😀
# spacebar -m config center_shell_command  "whoami"
# 
# echo "spacebar configuration loaded.."

#!/usr/bin/env sh

# spacebar -m config text_font "Helvetica Neue:Bold:12.0"
spacebar -m config icon_font "UbuntuCondensed Nerd Font:Regular:16.0"
# spacebar -m config background_color 0xff2e3440
# spacebar -m config foreground_color 0xffd8dee9
# spacebar -m config space_icon_strip      
# spacebar -m config power_icon_strip  
# spacebar -m config space_icon 
# spacebar -m config clock_icon 
# spacebar -m config clock_format "%a %R"

echo "spacebar configuration loaded.."
